version: 2
updates:

  # GHA
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  # Javascript
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      time: "04:00"
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
