on:
  push:
    tags:
      - '*-*-*'

name: Create release draft

jobs:
  build:
    name: Create release from tag
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: use node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: create release tarball
        run: echo 'y' | ./.github/create-release.sh

      - name: create new release
        uses: softprops/action-gh-release@v1
        with:
          files: oc-studio-*.tar.gz
          draft: true
          fail_on_unmatched_files: true
          generate_release_notes: true
